// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh6p3O9quobYBeSDtQc5SNB-BIrXHboRs',
    appId: '1:871204951466:web:cc9fc03c6671a1922107d3',
    messagingSenderId: '871204951466',
    projectId: 'habit-app-1867c',
    authDomain: 'habit-app-1867c.firebaseapp.com',
    storageBucket: 'habit-app-1867c.firebasestorage.app',
    measurementId: 'G-H80RLV0KYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV9srNtAiLM6BRLvaweN4nb0sTiXUPWmE',
    appId: '1:871204951466:android:57647485b020ce702107d3',
    messagingSenderId: '871204951466',
    projectId: 'habit-app-1867c',
    storageBucket: 'habit-app-1867c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6heu6R1gIcCCyn2nQygnmv9yQ7vBeP7Q',
    appId: '1:871204951466:ios:da1e54dadfec844d2107d3',
    messagingSenderId: '871204951466',
    projectId: 'habit-app-1867c',
    storageBucket: 'habit-app-1867c.firebasestorage.app',
    iosClientId: '871204951466-hkmi8fc0081sumch96f709vl1ug37iif.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6heu6R1gIcCCyn2nQygnmv9yQ7vBeP7Q',
    appId: '1:871204951466:ios:da1e54dadfec844d2107d3',
    messagingSenderId: '871204951466',
    projectId: 'habit-app-1867c',
    storageBucket: 'habit-app-1867c.firebasestorage.app',
    iosClientId: '871204951466-hkmi8fc0081sumch96f709vl1ug37iif.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh6p3O9quobYBeSDtQc5SNB-BIrXHboRs',
    appId: '1:871204951466:web:d00ecc16fd6cab282107d3',
    messagingSenderId: '871204951466',
    projectId: 'habit-app-1867c',
    authDomain: 'habit-app-1867c.firebaseapp.com',
    storageBucket: 'habit-app-1867c.firebasestorage.app',
    measurementId: 'G-2EXSG2LK0Q',
  );
}